### ISSUE TITLE
depstar is deprecated and archived; switch to tools.build

### ISSUE THREAD

**Issue by seancorfield** [helins/maestro.clj#1]
`depstar` has been deprecated and archived for six month now; I'm encouraging everyone to switch to `tools.build`. My `build-clj` wrapper makes it easier to switch.

**Comment by helins** [comment]
Makes sense, thanks for the heads-up

**Comment by seancorfield** [comment]
I was expecting to see it gone from `deps.edn` when you closed this as "completed" 😃

**Comment by helins** [comment]
Even better, I'm archiving the repo! I was merely delayed :)

All of this bloomed into a full-blown paradigm so to say: https://github.com/protosens/monorepo.cljc/tree/main/module/maestro

Cheers
